[context.production.enviroment]
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.enviroment]
    HUGO_VERSION = "0.55.6"
[[redirects]]
    from = "/"
    to = "bs"
    status = 302
    force = false
    conditions = {Language = ["bs","hr","sr"]}
[[redirects]]
    from = "/"
    to = "es"
    status = 302
    force = false
    conditions = {Language = ["es"]}
[[redirects]]
    from = "/"
    to = "en"
    status = 302
    force = false
    conditions = {Language = ["en"]}