[[redirects]]
    from = "/"
    to = "/bs"
    status = 302
    force = false
    conditions = {language = "bs,hr,sr"}
[[redirects]]
    from = "/"
    to = "/es"
    status = 302
    force = false
    conditions = {language = "es"}
[[redirects]]
    from = "/"
    to = "/en"
    status = 302
    force = false
    conditions = {language = "en"}