[build]
    publish = "public"
    command = "hugo"

[build.environment]
    HUGO_VERSION = "0.55.6"

[context.production.environment]
    HUGO_ENV = "production"


[[redirects]]
    from = "/"
    to = "/bs"
    status = 302
    force = false
    conditions = {language = "bs,hr,sr"}
[[redirects]]
    from = "/"
    to = "/es"
    status = 302
    force = false
    conditions = {language = "es"}
[[redirects]]
    from = "/"
    to = "/en"
    status = 302
    force = false
    conditions = {language = "en"}

