[build]
    publish = "public"
    command = "hugo --gc --minify"
[context.production.enviroment]
    HUGO_VERSION = "O.55.6"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.enviroment]
    HUGO_VERSION = "0.55.6"
[[redirects]]
    from = "/"
    to = "/bs"
    status = 302
    force = false
    conditions = {language = "bs,hr,sr"}
[[redirects]]
    from = "/"
    to = "/es"
    status = 302
    force = false
    conditions = {language = "es"}
[[redirects]]
    from = "/"
    to = "/en"
    status = 302
    force = false
    conditions = {language = "en"}

