[build]
    publish = "public"
    command = "hugo"

[build.environment]
    HUGO_VERSION = "0.50"

[context.production.environment]
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
    command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.55.6"

[context.branch-deploy]
    command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.55.6"



[[redirects]]
    from = "/"
    to = "/bs"
    status = 302
    force = false
    conditions = {language = "bs,hr,sr"}
[[redirects]]
    from = "/"
    to = "/es"
    status = 302
    force = false
    conditions = {language = "es"}
[[redirects]]
    from = "/"
    to = "/en"
    status = 302
    force = false
    conditions = {language = "en"}

